# Internal routing configuration to handle ESI
#_internal:
#    resource: "@FrameworkBundle/Resources/config/routing/internal.xml"
#    prefix:   /_internal

# General
_welcome:
    pattern:  /
    defaults: { _controller: OctopusFrontendBundle:Home:index }

_about:
    pattern:  /about
    defaults: { _controller: OctopusFrontendBundle:Home:about }

_report:
    resource: "@OctopusFrontendBundle/Controller/ReportController.php"
    type:     annotation
    prefix:   /report

# Login
login:
    pattern:  /login
    defaults: { _controller: OctopusSecurityBundle:Security:login }
login_check:
    pattern:  /login_check
logout:
    pattern:  /logout


# Demo
#_demo_secured:
#    resource: "@AcmeDemoBundle/Controller/SecuredController.php"
#    type:     annotation

#_demo:
#    resource: "@AcmeDemoBundle/Controller/DemoController.php"
#    type:     annotation
#    prefix:   /demo
