# Internal routing configuration to handle ESI
#_internal:
#    resource: "@FrameworkBundle/Resources/config/routing/internal.xml"
#    prefix:   /_internal

##
# General pages
_welcome:
    pattern:  /
    defaults: { _controller: OctopusFrontendBundle:Home:index }
#
_about:
    pattern:  /about
    defaults: { _controller: OctopusFrontendBundle:Home:about }
#
_save_report_query:
    pattern:  /saveReportQuery
    defaults: { _controller: OctopusFrontendBundle:Home:saveReportQuery }
#
_remove_report_query:
    pattern:  /removeReportQuery
    defaults: { _controller: OctopusFrontendBundle:Home:removeReportQuery }
##

##
# Reports
_report:
    resource: "@OctopusFrontendBundle/Controller/ReportController.php"
    type:     annotation
    prefix:   /report
##

##
# User manage
_myaccount:
    resource: "@OctopusUserBundle/Controller/MyAccountController.php"
    type:     annotation
    prefix:   /myaccount
#
_admin_manage_users:
    resource: "@OctopusUserBundle/Controller/AdminManageUsersController.php"
    type:     annotation
    prefix:   /admin/manage-users
##

##
# Authentication
login:
    pattern:  /login
    defaults: { _controller: OctopusSecurityBundle:Security:login }
#
login_check:
    pattern:  /login_check
#
logout:
    pattern:  /logout
##